# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Demo Mycroft Skills Repo/Site
email: joshymcd92@gmail.com
description: Demo/Example site for repo of mycroft skills
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshymcd.me" # the base hostname & protocol for your site
twitter_username: joshymcd92
github_username:  joshymcd

# Build settings
markdown: kramdown

collections:
  skills:
    output: true
    skill_type: "community"
    title: ""
    short_description: ""
    description: ""
    author: ""
    email: ""
    website: ""
    twitter_username: ""
    github_username: ""
    github_repo: ""
